METRIC_FORMATS = {
    'CHAR': 'B',
    'COMPLEX': 'dd',
    'DOUBLE': 'd',
    'FLOAT': 'd',
    # 'HISTOGRAM': lambda n: str(int(n)) + 'd',
    'INT': 'i',
    'INT16': 'h',
    'INT32': 'i',
    'INT64': 'q',
    'INT8': 'b',
    'INTEGER': 'q',
    'MAXDOUBLE': 'd',
    'MINDOUBLE': 'd',
    'NDOUBLES': lambda n: str(int(n)) + 'd',
    'RATE': 'dd',
    # 'SCALE_FUNC': 'P',
    'SHORT INT': 'h',
    'SIGNED INT': 'i',
    'SIGNED INTEGER': 'q',
    'SIGNED SHORT INT': 'h',
    'TAU_ATOMIC': 'Idddd',
    'UINT16': 'H',
    'UINT32': 'I',
    'UINT64': 'Q',
    'UINT8': 'B',
    'UNSIGNED INT': 'I',
    'UNSIGNED INTEGER': 'Q',
    'UNSIGNED SHORT INT': 'H',
}
